<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion><parent><groupId>io.github.markomijanovic</groupId><artifactId>distributed-shopping-system</artifactId><version>1.0-SNAPSHOT</version></parent>
  <artifactId>CentralniServer</artifactId><packaging>war</packaging>
  <dependencies><dependency><groupId>javax</groupId><artifactId>javaee-api</artifactId><scope>provided</scope></dependency></dependencies>
  <build><sourceDirectory>src/java</sourceDirectory><resources><resource><directory>src/conf</directory><targetPath>META-INF</targetPath><excludes><exclude>*.example</exclude><exclude>MANIFEST.MF</exclude></excludes></resource></resources><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-war-plugin</artifactId><configuration><warSourceDirectory>web</warSourceDirectory></configuration></plugin></plugins></build>
</project>
